ci: replace action with command line
the action gives a false diagnostic:
```
Error: Manifest needs the 'activationEvents' property, given it has a 'main' property.
```
since it's not needed as per https://code.visualstudio.com/api/references/activation-events#onCustomEditor